### PR TITLE
Pull request for Create a database based on a diagram

### PR DESCRIPTION
**Pull request by zuhebahmed88091**
### In this PR:

- [ ] Added database diagram 
sql_diagram

- [ ] Created a file named `schema_based_on_diagram.sql` where we implement the database from the diagram.

- [ ] Joined tables from many-to-many relationships might not appear in the diagram

- [ ] Added the FK indexes.

### Table details

- All tables info:

- patients table:

- Invoices table:

- invoce_items table:

- medical_histories table:

- treatments table:

- medical_treatment table: 

Thank you for reviewing our PR!

Regards,

@kimitaWanjohi @zuhebahmed88091

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @zuhebahmed88091  @kimitaWanjohi 👋🏼👋🏼👋🏼,

require_changes
 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Indexes have been created on all foreign keys👍🏼.
- [x] All foreigh keys are set as required👍🏼.
- [x] All tables in the diagram has been created👍🏼.


## Required Changes ♻️

- [ ] Kindly create a join table for the many-to-many relationship between the medical_histories and treatments as it is a requirement that all "join table" for the many-to-many relastionships is created, even if they are not showed on the diagram👍🏼.
image


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zuhebahmed88091** [comment]
Hello @Ibizugbe 

I already created a join table for the many-to-many relationship between the medical_histories and treatments. The join table name is medical_treatment. can you check again

**Comment by Ibizugbe** [comment]
@zuhebahmed88091  Thanks for the feedback, my bad🥲 I didn't see the table. but you still haven't referenced the foreign keys😉. I will just give you a call on zoom and guide you.. sorry for the inconveniences.

**Comment by zuhebahmed88091** [comment]
Already done that. Thank you

**Comment by Ibizugbe** [comment]
Alright, you can proceed to submit for a review since you already created the join table with the necessary foreign key references👍🏼.

Once again, sorry for the incoveniences🙏🏼.

**Comment by zuhebahmed88091** [comment]
Thank you

**Review by aamirkhan2478 — APPROVED** [review]
Hi @zuhebahmed88091 7 @kimitaWanjohi , 

GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
